---
title: "EDA"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Data

```{r}
#load(data)
devtools::load_all("msuwcRouting")
library(tidyverse)
load(file="./NewData/streamNet.RData")

#library(zoo)
library(reshape2)
load("./NewData/gaugePlotData.RData")
```



```{r}

```



## Plot precip and snowpack in lamar with lamar guage to investigate double peak

### Aggregate precip, snowpack for lamar

```{r}
# LPJ-Guess outputs of surface and subsurface runoff
precipPath <- "../NcDat/gye_output/GYE_Day3_2016_stand_monthly_prcp.nc"
snowPath <- "../NcDat/gye_output/GYE_Day3_2016_stand_monthly_spack.nc"

#sroSaveLocation <- "./NewData/surfaceRunoff.csv"
#ssroSaveLocation <- "./NewData/subsurfaceRunoff.csv"

precip <- AggregateMonthlyRunoff(ncFile=precipPath, streamNet = streamNet, startDate="1980-01-01")

snow <- AggregateMonthlyRunoff(ncFile=snowPath, streamNet = streamNet, startDate="1980-01-01")

snow <- replace(snow, is.na(snow), 0)
precip <- replace(precip, is.na(precip), 0)

nullSumModel <- function(dat, streamNet){
  
  for(i in 1:ncol(dat)){
    
    parents <- which(streamNet$data$NextDown == colnames(dat)[i])
    
    if(length(parents) == 1){
      dat[,i] <- dat[, i] + dat[, parents]
    } else if(length(parents) > 1){
      dat[,i] <- dat[, i] + rowSums(dat[, parents])
    } else {
      dat[,i]
    }
  }
  return(dat)
}

snowSum <- nullSumModel(snow, streamNet)
precipSum <- nullSumModel(precip, streamNet)

snowSumKm <- sweep(snowSum, 2, streamNet$data$ContribArea, "/")
precipSumKm <- sweep(precipSum, 2, streamNet$data$ContribArea, "/")
```


```{r fig.height = 4, fig.width= 10}
colToPlot <- "21647"
flow %>% 
  select(date, colToPlot) %>% 
  bind_cols(select(gaugeDatMonthly, colToPlot)) %>% 
  bind_cols(select(snowSumKm, colToPlot)) %>% 
  bind_cols(select(precipSumKm, colToPlot)) %>% 
  tail(100) %>% 
  melt(id.vars = "date") %>% 
  ggplot() +
    geom_path(aes(x = date, y = value, color = variable)) +
    labs(y = "Flow (m3/sec)", x = "Year", color = "Data Source") +
    ggtitle(filter(gaugeNames, ID == colToPlot)$Name) +
    scale_color_manual(values = c("red", "black", "lightblue", "blue"), labels = c("Simulated", "Observed", "Snow", "Precip")) +
    theme_bw() +
    theme(plot.title = element_text(hjust = 0.5))
```


